/**
 * @fileoverview AGENTS.md 标准格式输出器
 * @description 将 AgentsConfig 对象转换为标准 AGENTS.md 格式文本
 */

import {
  AgentsConfig,
  AgentsSection,
  DirectiveCategory,
} from '../core/types';

/** 类别标题映射 */
const CATEGORY_TITLES: Record<DirectiveCategory, string> = {
  [DirectiveCategory.CODE_STYLE]: 'Code Style & Formatting',
  [DirectiveCategory.ARCHITECTURE]: 'Architecture & Patterns',
  [DirectiveCategory.TESTING]: 'Testing',
  [DirectiveCategory.DOCUMENTATION]: 'Documentation',
  [DirectiveCategory.WORKFLOW]: 'Workflow & CI/CD',
  [DirectiveCategory.DEPENDENCIES]: 'Dependencies',
  [DirectiveCategory.SECURITY]: 'Security',
  [DirectiveCategory.PERFORMANCE]: 'Performance',
  [DirectiveCategory.GENERAL]: 'General Guidelines',
};

export class AgentsFormatter {
  /**
   * 将 AgentsConfig 格式化为 AGENTS.md 文本
   * @param config - AGENTS.md 标准配置对象
   * @returns 格式化后的 Markdown 文本
   */
  format(config: AgentsConfig): string {
    const lines: string[] = [];

    lines.push(this.formatHeader(config));
    lines.push(this.formatMetadata(config));
    lines.push(this.formatTechStack(config));

    for (const section of config.sections) {
      if (section.directives.length > 0) {
        lines.push(this.formatSection(section));
      }
    }

    lines.push(this.formatFooter(config));

    return lines.join('\n');
  }

  /**
   * 格式化文件头
   * @param config - 配置对象
   * @returns 格式化的头部文本
   */
  private formatHeader(config: AgentsConfig): string {
    let header = `# ${config.projectName}\n\n`;
    if (config.description) {
      header += `> ${config.description}\n\n`;
    }
    return header;
  }

  /**
   * 格式化元数据段
   * @param config - 配置对象
   * @returns 格式化的元数据文本
   */
  private formatMetadata(config: AgentsConfig): string {
    let meta = '---\n';
    meta += `version: ${config.version}\n`;
    meta += `generated: ${config.generatedAt}\n`;
    meta += `sources: ${config.sources.join(', ')}\n`;
    meta += '---\n\n';
    return meta;
  }

  /**
   * 格式化技术栈段
   * @param config - 配置对象
   * @returns 格式化的技术栈文本
   */
  private formatTechStack(config: AgentsConfig): string {
    if (!config.techStack.length) return '';

    let text = '## Tech Stack\n\n';
    for (const tech of config.techStack) {
      text += `- ${tech}\n`;
    }
    text += '\n';
    return text;
  }

  /**
   * 格式化一个配置段落
   * @param section - 配置段落对象
   * @returns 格式化的段落文本
   */
  private formatSection(section: AgentsSection): string {
    const title = section.title || CATEGORY_TITLES[section.category] || 'Other';
    let text = `## ${title}\n\n`;

    const sorted = [...section.directives].sort((a, b) => b.priority - a.priority);

    for (const directive of sorted) {
      const content = directive.content.trim();
      if (content.includes('\n')) {
        text += `${content}\n\n`;
      } else {
        text += `- ${content}\n`;
      }
    }

    text += '\n';
    return text;
  }

  /**
   * 格式化文件尾
   * @param config - 配置对象
   * @returns 格式化的尾部文本
   */
  private formatFooter(config: AgentsConfig): string {
    let footer = '---\n\n';
    footer += `*Generated by [AgentSync](https://github.com/agentsync) v${config.version}*\n`;
    footer += `*Last updated: ${config.generatedAt}*\n`;
    return footer;
  }

  /**
   * 获取类别的标准标题
   * @param category - 指令类别
   * @returns 标准标题
   */
  getCategoryTitle(category: DirectiveCategory): string {
    return CATEGORY_TITLES[category];
  }
}
