import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { Quote, UserSettings } from "@/types";
import { formatCurrency } from "./utils";

/**
 * @description 生成 PDF 报价单
 * @param {Quote} quote - 报价单数据
 * @param {UserSettings} settings - 用户设置
 * @returns {jsPDF} PDF 文档实例
 */
export function generateQuotePDF(
  quote: Quote,
  settings: UserSettings
): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(24);
  doc.setTextColor(13, 148, 136);
  doc.text(settings.businessName || "QuoteSwift", 20, 30);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  let infoY = 38;
  if (settings.ownerName) { doc.text(settings.ownerName, 20, infoY); infoY += 6; }
  if (settings.email) { doc.text(settings.email, 20, infoY); infoY += 6; }
  if (settings.phone) { doc.text(settings.phone, 20, infoY); infoY += 6; }
  if (settings.address) { doc.text(settings.address, 20, infoY); }

  doc.setFontSize(20);
  doc.setTextColor(30, 41, 59);
  doc.text("QUOTE", pageWidth - 20, 30, { align: "right" });

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`#${quote.quoteNumber}`, pageWidth - 20, 38, { align: "right" });
  doc.text(
    `Date: ${new Date(quote.createdAt).toLocaleDateString()}`,
    pageWidth - 20, 44, { align: "right" }
  );
  doc.text(
    `Valid Until: ${new Date(quote.validUntil).toLocaleDateString()}`,
    pageWidth - 20, 50, { align: "right" }
  );

  doc.setDrawColor(226, 232, 240);
  doc.line(20, 68, pageWidth - 20, 68);

  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  doc.text("Prepared For:", 20, 78);
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  let clientY = 85;
  doc.text(quote.customer.name, 20, clientY); clientY += 6;
  if (quote.customer.email) { doc.text(quote.customer.email, 20, clientY); clientY += 6; }
  if (quote.customer.phone) { doc.text(quote.customer.phone, 20, clientY); clientY += 6; }
  if (quote.customer.address) { doc.text(quote.customer.address, 20, clientY); }

  autoTable(doc, {
    startY: 105,
    head: [["Description", "Qty", "Unit", "Unit Price", "Total"]],
    body: quote.items.map((item) => [
      item.description,
      item.quantity.toString(),
      item.unit,
      formatCurrency(item.unitPrice, settings.currency),
      formatCurrency(item.quantity * item.unitPrice, settings.currency),
    ]),
    headStyles: {
      fillColor: [13, 148, 136],
      textColor: [255, 255, 255],
      fontSize: 10,
    },
    bodyStyles: { fontSize: 10 },
    alternateRowStyles: { fillColor: [240, 253, 250] },
    margin: { left: 20, right: 20 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const finalY = ((doc as any).lastAutoTable?.finalY as number) ?? 180;

  const summaryX = pageWidth - 80;
  let summaryY = finalY + 15;

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text("Subtotal:", summaryX, summaryY);
  doc.text(
    formatCurrency(quote.subtotal, settings.currency),
    pageWidth - 20, summaryY, { align: "right" }
  );

  summaryY += 8;
  doc.text(`Tax (${settings.taxRate}%):`, summaryX, summaryY);
  doc.text(
    formatCurrency(quote.tax, settings.currency),
    pageWidth - 20, summaryY, { align: "right" }
  );

  summaryY += 10;
  doc.setFontSize(14);
  doc.setTextColor(13, 148, 136);
  doc.text("Total:", summaryX, summaryY);
  doc.text(
    formatCurrency(quote.total, settings.currency),
    pageWidth - 20, summaryY, { align: "right" }
  );

  if (quote.notes) {
    summaryY += 20;
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text("Notes:", 20, summaryY);
    const splitNotes = doc.splitTextToSize(quote.notes, pageWidth - 40);
    doc.text(splitNotes, 20, summaryY + 7);
  }

  summaryY += 40;
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by QuoteSwift", pageWidth / 2, summaryY, { align: "center" });

  return doc;
}

/**
 * @description 下载 PDF 报价单
 * @param {Quote} quote - 报价单数据
 * @param {UserSettings} settings - 用户设置
 */
export function downloadQuotePDF(
  quote: Quote,
  settings: UserSettings
): void {
  const doc = generateQuotePDF(quote, settings);
  doc.save(`quote-${quote.quoteNumber}.pdf`);
}
