/**
 * @fileoverview PDF 发票生成模块 - 使用 jsPDF 生成符合规范的 PDF 发票
 */

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { Invoice } from "@/types";

/**
 * 生成 PDF 发票
 * @param {Invoice} invoice - 发票数据
 * @returns {Blob} PDF 文件的 Blob 对象
 */
export function generateInvoicePDF(invoice: Invoice): Blob {
  const doc = new jsPDF();

  doc.setFontSize(24);
  doc.setTextColor(33, 33, 33);
  doc.text("INVOICE", 20, 30);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Invoice #: ${invoice.invoiceNumber}`, 20, 42);
  doc.text(`Date: ${formatDate(invoice.createdAt)}`, 20, 48);
  doc.text(`Due: ${formatDate(invoice.dueDate)}`, 20, 54);

  // Status badge
  doc.setFontSize(12);
  const statusColor = getStatusColor(invoice.status);
  doc.setTextColor(statusColor.r, statusColor.g, statusColor.b);
  doc.text(invoice.status.toUpperCase(), 160, 30);

  // From section
  doc.setFontSize(10);
  doc.setTextColor(33, 33, 33);
  doc.text("From:", 20, 70);
  doc.setTextColor(66, 66, 66);
  doc.text(invoice.from.name, 20, 76);
  doc.text(invoice.from.email, 20, 82);
  if (invoice.from.address) doc.text(invoice.from.address, 20, 88);
  if (invoice.from.taxId) doc.text(`Tax ID: ${invoice.from.taxId}`, 20, 94);

  // To section
  doc.setTextColor(33, 33, 33);
  doc.text("To:", 120, 70);
  doc.setTextColor(66, 66, 66);
  doc.text(invoice.to.name, 120, 76);
  doc.text(invoice.to.email, 120, 82);
  if (invoice.to.address) doc.text(invoice.to.address, 120, 88);
  if (invoice.to.taxId) doc.text(`Tax ID: ${invoice.to.taxId}`, 120, 94);

  // Items table
  const tableData = invoice.items.map((item) => [
    item.description,
    item.quantity.toString(),
    formatCurrency(item.unitPrice, invoice.currency),
    formatCurrency(item.total, invoice.currency),
  ]);

  autoTable(doc, {
    startY: 110,
    head: [["Description", "Qty", "Unit Price", "Total"]],
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: [59, 130, 246],
      textColor: [255, 255, 255],
      fontSize: 10,
    },
    bodyStyles: { fontSize: 9, textColor: [50, 50, 50] },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });

  const finalY = ((doc as unknown as Record<string, { finalY?: number }>).lastAutoTable?.finalY) || 160;

  // Totals
  const totalsX = 140;
  doc.setFontSize(10);
  doc.setTextColor(66, 66, 66);
  doc.text("Subtotal:", totalsX, finalY + 15);
  doc.text(
    formatCurrency(invoice.subtotal, invoice.currency),
    175,
    finalY + 15
  );

  doc.text(`Tax (${invoice.taxRate}%):`, totalsX, finalY + 22);
  doc.text(
    formatCurrency(invoice.taxAmount, invoice.currency),
    175,
    finalY + 22
  );

  doc.setFontSize(12);
  doc.setTextColor(33, 33, 33);
  doc.text("Total:", totalsX, finalY + 32);
  doc.text(formatCurrency(invoice.total, invoice.currency), 175, finalY + 32);

  // Notes
  if (invoice.notes) {
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text("Notes:", 20, finalY + 50);
    doc.text(invoice.notes, 20, finalY + 56);
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by InvoiceFlow AI", 20, 285);

  return doc.output("blob");
}

/**
 * 下载 PDF 文件
 * @param {Blob} blob - PDF Blob 对象
 * @param {string} filename - 文件名
 */
export function downloadPDF(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * 计算发票金额汇总
 * @param {Array<{quantity: number; unitPrice: number}>} items - 发票项目列表
 * @param {number} taxRate - 税率（百分比）
 * @returns {{ subtotal: number; taxAmount: number; total: number }}
 */
export function calculateTotals(
  items: { quantity: number; unitPrice: number }[],
  taxRate: number
): { subtotal: number; taxAmount: number; total: number } {
  const subtotal = items.reduce(
    (sum, item) => sum + item.quantity * item.unitPrice,
    0
  );
  const taxAmount = subtotal * (taxRate / 100);
  const total = subtotal + taxAmount;

  return {
    subtotal: Math.round(subtotal * 100) / 100,
    taxAmount: Math.round(taxAmount * 100) / 100,
    total: Math.round(total * 100) / 100,
  };
}

/**
 * 生成发票编号
 * @param {number} [sequence] - 序列号
 * @returns {string} 发票编号
 */
export function generateInvoiceNumber(sequence?: number): string {
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const seq = String(sequence || Math.floor(Math.random() * 9999)).padStart(
    4,
    "0"
  );
  return `INV-${year}${month}-${seq}`;
}

/** 格式化日期 */
function formatDate(dateStr: string): string {
  try {
    return new Date(dateStr).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  } catch {
    return dateStr;
  }
}

/** 格式化货币 */
function formatCurrency(amount: number, currency: string): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: currency || "USD",
  }).format(amount);
}

/** 获取状态颜色 */
function getStatusColor(
  status: string
): { r: number; g: number; b: number } {
  const colors: Record<string, { r: number; g: number; b: number }> = {
    draft: { r: 107, g: 114, b: 128 },
    sent: { r: 59, g: 130, b: 246 },
    paid: { r: 34, g: 197, b: 94 },
    overdue: { r: 239, g: 68, b: 68 },
    cancelled: { r: 156, g: 163, b: 175 },
  };
  return colors[status] || colors.draft;
}
