/**
 * @fileoverview AI 助手配置文件模板定义
 */

import { ConfigTemplate } from "@/types";

/** Cursor Rules 模板 */
const cursorTemplate: ConfigTemplate = {
  id: "cursor-rules",
  name: "Cursor Rules",
  assistant: "cursor",
  description: "生成 .cursorrules 配置文件，为 Cursor AI 提供项目上下文",
  icon: "cursor",
  fileName: ".cursorrules",
  content: `# Project: {{PROJECT_NAME}}
# Generated by ConfigSync AI

## Project Overview
{{PROJECT_DESCRIPTION}}

## Tech Stack
{{TECH_STACK}}

## Project Structure
{{PROJECT_STRUCTURE}}

## Coding Conventions
- Use {{LANGUAGE}} as the primary language
- Follow {{FRAMEWORK}} best practices
- Use consistent naming conventions

## Key Dependencies
{{DEPENDENCIES}}

## Important Notes
{{NOTES}}
`,
  variables: [
    { key: "PROJECT_NAME", label: "项目名称", description: "项目名称", defaultValue: "My Project" },
    { key: "PROJECT_DESCRIPTION", label: "项目描述", description: "简要描述项目功能", defaultValue: "A web application" },
    { key: "TECH_STACK", label: "技术栈", description: "使用的技术栈", defaultValue: "TypeScript, React, Next.js" },
    { key: "PROJECT_STRUCTURE", label: "项目结构", description: "自动生成的项目结构", defaultValue: "" },
    { key: "LANGUAGE", label: "主要语言", description: "项目主要编程语言", defaultValue: "TypeScript" },
    { key: "FRAMEWORK", label: "框架", description: "使用的主要框架", defaultValue: "Next.js" },
    { key: "DEPENDENCIES", label: "依赖", description: "关键依赖列表", defaultValue: "" },
    { key: "NOTES", label: "备注", description: "其他重要信息", defaultValue: "" },
  ],
};

/** Codex 配置模板 */
const codexTemplate: ConfigTemplate = {
  id: "codex-instructions",
  name: "Codex Instructions",
  assistant: "codex",
  description: "生成 AGENTS.md 指令文件，为 OpenAI Codex 提供编码指南",
  icon: "codex",
  fileName: "AGENTS.md",
  content: `# Codex Agent Instructions
# Project: {{PROJECT_NAME}}
# Generated by ConfigSync AI

## Overview
{{PROJECT_DESCRIPTION}}

## Tech Stack
{{TECH_STACK}}

## Project Structure
\`\`\`
{{PROJECT_STRUCTURE}}
\`\`\`

## Development Guidelines
- Primary language: {{LANGUAGE}}
- Framework: {{FRAMEWORK}}
- Always follow existing code patterns and conventions
- Write tests for new functionality
- Keep functions small and focused

## Key Dependencies
{{DEPENDENCIES}}

## Testing
- Run tests with: {{TEST_COMMAND}}
- Ensure all tests pass before committing

## Notes
{{NOTES}}
`,
  variables: [
    { key: "PROJECT_NAME", label: "项目名称", description: "项目名称", defaultValue: "My Project" },
    { key: "PROJECT_DESCRIPTION", label: "项目描述", description: "简要描述项目功能", defaultValue: "A web application" },
    { key: "TECH_STACK", label: "技术栈", description: "使用的技术栈", defaultValue: "TypeScript, React, Next.js" },
    { key: "PROJECT_STRUCTURE", label: "项目结构", description: "自动生成的项目结构", defaultValue: "" },
    { key: "LANGUAGE", label: "主要语言", description: "项目主要编程语言", defaultValue: "TypeScript" },
    { key: "FRAMEWORK", label: "框架", description: "使用的主要框架", defaultValue: "Next.js" },
    { key: "DEPENDENCIES", label: "依赖", description: "关键依赖列表", defaultValue: "" },
    { key: "TEST_COMMAND", label: "测试命令", description: "运行测试的命令", defaultValue: "npm test" },
    { key: "NOTES", label: "备注", description: "其他重要信息", defaultValue: "" },
  ],
};

/** Claude Code 配置模板 */
const claudeCodeTemplate: ConfigTemplate = {
  id: "claude-code-md",
  name: "Claude Code CLAUDE.md",
  assistant: "claude-code",
  description: "生成 CLAUDE.md 配置文件，为 Claude Code 提供项目上下文",
  icon: "claude",
  fileName: "CLAUDE.md",
  content: `# CLAUDE.md
# Project: {{PROJECT_NAME}}
# Generated by ConfigSync AI

## Project Description
{{PROJECT_DESCRIPTION}}

## Technology Stack
{{TECH_STACK}}

## Repository Structure
\`\`\`
{{PROJECT_STRUCTURE}}
\`\`\`

## Development Setup
- Language: {{LANGUAGE}}
- Framework: {{FRAMEWORK}}
- Build: {{BUILD_COMMAND}}
- Test: {{TEST_COMMAND}}
- Lint: {{LINT_COMMAND}}

## Coding Standards
- Follow existing patterns in the codebase
- Use meaningful variable and function names
- Add JSDoc comments for public APIs
- Keep commits focused and well-described

## Key Dependencies
{{DEPENDENCIES}}

## Additional Context
{{NOTES}}
`,
  variables: [
    { key: "PROJECT_NAME", label: "项目名称", description: "项目名称", defaultValue: "My Project" },
    { key: "PROJECT_DESCRIPTION", label: "项目描述", description: "简要描述项目功能", defaultValue: "A web application" },
    { key: "TECH_STACK", label: "技术栈", description: "使用的技术栈", defaultValue: "TypeScript, React, Next.js" },
    { key: "PROJECT_STRUCTURE", label: "项目结构", description: "自动生成的项目结构", defaultValue: "" },
    { key: "LANGUAGE", label: "主要语言", description: "项目主要编程语言", defaultValue: "TypeScript" },
    { key: "FRAMEWORK", label: "框架", description: "使用的主要框架", defaultValue: "Next.js" },
    { key: "BUILD_COMMAND", label: "构建命令", description: "构建项目的命令", defaultValue: "npm run build" },
    { key: "TEST_COMMAND", label: "测试命令", description: "运行测试的命令", defaultValue: "npm test" },
    { key: "LINT_COMMAND", label: "Lint 命令", description: "运行代码检查的命令", defaultValue: "npm run lint" },
    { key: "DEPENDENCIES", label: "依赖", description: "关键依赖列表", defaultValue: "" },
    { key: "NOTES", label: "备注", description: "其他重要信息", defaultValue: "" },
  ],
};

/** GitHub Copilot 配置模板 */
const copilotTemplate: ConfigTemplate = {
  id: "copilot-instructions",
  name: "Copilot Instructions",
  assistant: "copilot",
  description: "生成 .github/copilot-instructions.md，为 GitHub Copilot 提供项目指南",
  icon: "copilot",
  fileName: ".github/copilot-instructions.md",
  content: `# Copilot Instructions
# Project: {{PROJECT_NAME}}
# Generated by ConfigSync AI

## About This Project
{{PROJECT_DESCRIPTION}}

## Tech Stack
{{TECH_STACK}}

## Structure
{{PROJECT_STRUCTURE}}

## Conventions
- Language: {{LANGUAGE}}
- Framework: {{FRAMEWORK}}
- Prefer functional components and hooks
- Use TypeScript strict mode

## Dependencies
{{DEPENDENCIES}}

## Notes
{{NOTES}}
`,
  variables: [
    { key: "PROJECT_NAME", label: "项目名称", description: "项目名称", defaultValue: "My Project" },
    { key: "PROJECT_DESCRIPTION", label: "项目描述", description: "简要描述项目功能", defaultValue: "A web application" },
    { key: "TECH_STACK", label: "技术栈", description: "使用的技术栈", defaultValue: "TypeScript, React, Next.js" },
    { key: "PROJECT_STRUCTURE", label: "项目结构", description: "自动生成的项目结构", defaultValue: "" },
    { key: "LANGUAGE", label: "主要语言", description: "项目主要编程语言", defaultValue: "TypeScript" },
    { key: "FRAMEWORK", label: "框架", description: "使用的主要框架", defaultValue: "Next.js" },
    { key: "DEPENDENCIES", label: "依赖", description: "关键依赖列表", defaultValue: "" },
    { key: "NOTES", label: "备注", description: "其他重要信息", defaultValue: "" },
  ],
};

/** Windsurf 配置模板 */
const windsurfTemplate: ConfigTemplate = {
  id: "windsurf-rules",
  name: "Windsurf Rules",
  assistant: "windsurf",
  description: "生成 .windsurfrules 配置文件，为 Windsurf AI 提供项目上下文",
  icon: "windsurf",
  fileName: ".windsurfrules",
  content: `# Windsurf Rules
# Project: {{PROJECT_NAME}}
# Generated by ConfigSync AI

## Project Info
{{PROJECT_DESCRIPTION}}

## Stack
{{TECH_STACK}}

## File Structure
{{PROJECT_STRUCTURE}}

## Guidelines
- Use {{LANGUAGE}} throughout
- Follow {{FRAMEWORK}} conventions
- Maintain consistent code style

## Packages
{{DEPENDENCIES}}

## Extra Info
{{NOTES}}
`,
  variables: [
    { key: "PROJECT_NAME", label: "项目名称", description: "项目名称", defaultValue: "My Project" },
    { key: "PROJECT_DESCRIPTION", label: "项目描述", description: "简要描述项目功能", defaultValue: "A web application" },
    { key: "TECH_STACK", label: "技术栈", description: "使用的技术栈", defaultValue: "TypeScript, React, Next.js" },
    { key: "PROJECT_STRUCTURE", label: "项目结构", description: "自动生成的项目结构", defaultValue: "" },
    { key: "LANGUAGE", label: "主要语言", description: "项目主要编程语言", defaultValue: "TypeScript" },
    { key: "FRAMEWORK", label: "框架", description: "使用的主要框架", defaultValue: "Next.js" },
    { key: "DEPENDENCIES", label: "依赖", description: "关键依赖列表", defaultValue: "" },
    { key: "NOTES", label: "备注", description: "其他重要信息", defaultValue: "" },
  ],
};

/** 所有可用模板 */
export const allTemplates: ConfigTemplate[] = [
  cursorTemplate,
  codexTemplate,
  claudeCodeTemplate,
  copilotTemplate,
  windsurfTemplate,
];

/**
 * 根据 AI 助手类型获取模板
 * @param assistant - AI 助手类型
 * @returns 匹配的模板
 */
export function getTemplateByAssistant(assistant: string): ConfigTemplate | undefined {
  return allTemplates.find((t) => t.assistant === assistant);
}

/**
 * 根据模板 ID 获取模板
 * @param id - 模板 ID
 * @returns 匹配的模板
 */
export function getTemplateById(id: string): ConfigTemplate | undefined {
  return allTemplates.find((t) => t.id === id);
}
