import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { PricingRecommendation, ValueInput } from "@/types";
import { INDUSTRY_CONFIG } from "./pricing";
import { formatCurrency, customerSizeLabel } from "./utils";

/**
 * @description 生成定价策略 PDF 报告
 * @param {PricingRecommendation} rec - 定价推荐结果
 * @param {ValueInput} input - 原始输入数据
 */
export function generatePricingPDF(
  rec: PricingRecommendation,
  input: ValueInput
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  doc.setFontSize(22);
  doc.setTextColor(124, 58, 237);
  doc.text("ValuePricer", pageWidth / 2, y, { align: "center" });
  y += 8;
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text("B2B SaaS Pricing Strategy Report", pageWidth / 2, y, {
    align: "center",
  });
  y += 12;

  doc.setDrawColor(124, 58, 237);
  doc.setLineWidth(0.5);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text("Product Overview", 20, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);

  const overviewData = [
    ["Product Name", rec.productName],
    ["Industry", INDUSTRY_CONFIG[rec.industry].label],
    ["Target Customer", customerSizeLabel(input.targetCustomerSize)],
    ["Engineers Impacted", `${input.engineerCount}`],
    ["Hours Saved / Week", `${input.hoursSavedPerWeek}h`],
    ["Avg Hourly Cost", formatCurrency(input.avgHourlyCost)],
    ["Additional Monthly Savings", formatCurrency(input.additionalCostSavingsMonthly)],
  ];

  autoTable(doc, {
    startY: y,
    head: [],
    body: overviewData,
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 3 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 60 },
      1: { cellWidth: 100 },
    },
    margin: { left: 20 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 12;

  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text("Value Analysis", 20, y);
  y += 8;

  const valueData = [
    ["Monthly Value Delivered", formatCurrency(rec.totalValueDelivered)],
    ["Recommended Model", rec.recommendedModel.replace(/_/g, " ").toUpperCase()],
    ["Customer ROI", `${rec.roi.toFixed(1)}x`],
  ];

  autoTable(doc, {
    startY: y,
    head: [],
    body: valueData,
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 3 },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 60 },
      1: { cellWidth: 100 },
    },
    margin: { left: 20 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 8;
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  const reasoningLines = doc.splitTextToSize(rec.modelReasoning, pageWidth - 40);
  doc.text(reasoningLines, 20, y);
  y += reasoningLines.length * 5 + 10;

  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text("Recommended Pricing Tiers", 20, y);
  y += 8;

  const tierData = rec.tiers.map((tier) => [
    tier.name,
    formatCurrency(tier.monthlyPrice) + "/mo",
    formatCurrency(tier.annualPrice) + "/yr",
    `${(tier.valueCapture * 100).toFixed(1)}%`,
    tier.features.slice(0, 3).join(", "),
  ]);

  autoTable(doc, {
    startY: y,
    head: [["Tier", "Monthly", "Annual", "Value Capture", "Key Features"]],
    body: tierData,
    theme: "grid",
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: {
      fillColor: [124, 58, 237],
      textColor: [255, 255, 255],
    },
    margin: { left: 20, right: 20 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 12;

  if (y > 250) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text("Key Insights", 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  rec.keyInsights.forEach((insight) => {
    const lines = doc.splitTextToSize(`• ${insight}`, pageWidth - 40);
    if (y + lines.length * 5 > 280) {
      doc.addPage();
      y = 20;
    }
    doc.text(lines, 20, y);
    y += lines.length * 5 + 3;
  });

  y += 5;
  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text("Competitor Analysis", 20, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  const compLines = doc.splitTextToSize(rec.competitorComparison, pageWidth - 40);
  doc.text(compLines, 20, y);

  y += compLines.length * 5 + 15;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by ValuePricer | ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    285,
    { align: "center" }
  );

  doc.save(`${rec.productName}-pricing-strategy.pdf`);
}
