/**
 * @fileoverview 模拟数据，用于开发和演示
 */

import type { Policy, RiskAssessment, OperationGuide, CaseStudy, SubscriptionPlan } from "@/types";

/** 模拟政策数据 */
export const mockPolicies: Policy[] = [
  {
    id: "pol-001",
    title: "Digital Markets Act (DMA) - New Compliance Requirements",
    titleCn: "《数字市场法》(DMA) — 新合规要求",
    country: "EU",
    category: "数据保护",
    summary: "The EU Digital Markets Act introduces new obligations for gatekeeper platforms, affecting Chinese tech companies operating in the European market.",
    summaryCn: "欧盟《数字市场法》对守门人平台提出新义务，影响在欧洲市场运营的中国科技企业。平台需确保数据互通性、禁止自我优待、允许用户卸载预装应用等。违反规定可面临全球营业额10%的罚款。",
    content: "The Digital Markets Act (DMA) establishes new rules for large online platforms designated as 'gatekeepers'. Key requirements include: interoperability of messaging services, allowing third-party app stores, prohibiting self-preferencing in rankings, and providing advertisers access to performance data. Chinese companies with significant EU user bases must assess their compliance obligations and implement necessary changes before the enforcement deadline.",
    sourceUrl: "https://digital-strategy.ec.europa.eu/en/policies/digital-markets-act",
    sourceName: "欧盟数字战略委员会",
    publishedAt: "2026-03-15T08:00:00Z",
    riskLevel: "high",
    affectedIndustries: ["科技", "电商", "社交媒体"],
  },
  {
    id: "pol-002",
    title: "US CHIPS Act Export Control Updates",
    titleCn: "美国《芯片法案》出口管制更新",
    country: "US",
    category: "贸易",
    summary: "Updated export controls on semiconductor technology targeting Chinese companies, with new licensing requirements for advanced chip exports.",
    summaryCn: "美国更新半导体技术出口管制，针对中国企业实施新的许可证要求。先进芯片及制造设备出口受限，涉及14nm以下制程技术。中国半导体企业需评估供应链影响并寻找替代方案。",
    content: "The U.S. Department of Commerce has issued updated export control rules under the CHIPS and Science Act, expanding restrictions on semiconductor exports to China. The new rules require licenses for exports of advanced computing chips, semiconductor manufacturing equipment, and related technology. Companies must conduct due diligence on end-users and end-uses to ensure compliance.",
    sourceUrl: "https://www.commerce.gov/chips",
    sourceName: "美国商务部",
    publishedAt: "2026-03-10T14:00:00Z",
    riskLevel: "critical",
    affectedIndustries: ["半导体", "科技", "电子制造"],
  },
  {
    id: "pol-003",
    title: "Japan Revised Immigration Control Act",
    titleCn: "日本修订《入境管理及难民认定法》",
    country: "JP",
    category: "劳工",
    summary: "Japan updates immigration policies to attract skilled foreign workers, creating new visa categories relevant to Chinese companies expanding to Japan.",
    summaryCn: "日本更新移民政策以吸引外国技术人才，新设\"特定技能2号\"签证类别。中国企业赴日设立分公司时，可通过新签证制度更便捷地派遣技术人员。但需满足日语能力、技能测试等条件。",
    content: "The revised Immigration Control Act introduces expanded visa categories for skilled workers. The 'Specified Skilled Worker No. 2' visa now covers 11 sectors including IT, manufacturing, and services. Chinese companies establishing operations in Japan can leverage these new pathways for employee transfers and local hiring.",
    sourceUrl: "https://www.moj.go.jp/isa/",
    sourceName: "日本法务省",
    publishedAt: "2026-03-08T06:00:00Z",
    riskLevel: "low",
    affectedIndustries: ["科技", "制造", "服务"],
  },
  {
    id: "pol-004",
    title: "Singapore Personal Data Protection Act Amendment",
    titleCn: "新加坡《个人数据保护法》修正案",
    country: "SG",
    category: "数据保护",
    summary: "Singapore strengthens data protection requirements with mandatory breach notification and increased penalties.",
    summaryCn: "新加坡加强数据保护要求，强制数据泄露通知制度，并提高处罚上限至1000万新元或年营业额10%。中国出海企业需完善数据保护体系，建立72小时内的数据泄露报告机制。",
    content: "The PDPA amendment strengthens Singapore's data protection framework. Key changes include mandatory data breach notification within 72 hours, increased financial penalties up to SGD 10 million or 10% of annual turnover, and new requirements for data portability. Organizations must appoint a Data Protection Officer and maintain comprehensive data inventories.",
    sourceUrl: "https://www.pdpc.gov.sg/",
    sourceName: "新加坡个人数据保护委员会",
    publishedAt: "2026-03-05T10:00:00Z",
    riskLevel: "medium",
    affectedIndustries: ["科技", "金融", "电商", "医疗"],
  },
  {
    id: "pol-005",
    title: "Vietnam E-Commerce Decree Update",
    titleCn: "越南电商新规更新",
    country: "VN",
    category: "外资准入",
    summary: "Vietnam introduces new regulations for cross-border e-commerce platforms, including local entity requirements and tax obligations.",
    summaryCn: "越南发布跨境电商新规，要求外国电商平台在越南设立本地实体或指定代理人。新规明确了增值税代扣代缴义务，以及消费者权益保护要求。中国跨境电商卖家需在6个月内完成合规调整。",
    content: "Vietnam's new e-commerce decree requires foreign platforms to establish local entities or appoint authorized representatives. The decree mandates VAT withholding obligations for cross-border sales, consumer protection compliance, and product safety certifications. A 6-month transition period is provided for existing operators.",
    sourceUrl: "https://www.moit.gov.vn/",
    sourceName: "越南工贸部",
    publishedAt: "2026-03-01T07:00:00Z",
    riskLevel: "high",
    affectedIndustries: ["电商", "零售", "物流"],
  },
  {
    id: "pol-006",
    title: "Indonesia Halal Product Assurance Law",
    titleCn: "印尼清真产品保证法实施细则",
    country: "ID",
    category: "消费者保护",
    summary: "Indonesia enforces mandatory halal certification for food, cosmetics, and pharmaceutical products entering the market.",
    summaryCn: "印尼全面实施清真产品认证制度，食品、化妆品、药品等必须获得清真认证才能在印尼市场销售。中国出口企业需在产品生产全链条确保清真合规，认证周期约3-6个月。",
    content: "The implementation of Indonesia's Halal Product Assurance Law requires all food, beverages, cosmetics, pharmaceuticals, and chemical products to obtain halal certification before being sold in Indonesia. The certification process involves production facility audits, ingredient verification, and ongoing compliance monitoring.",
    sourceUrl: "https://www.halal.go.id/",
    sourceName: "印尼清真产品保证局",
    publishedAt: "2026-02-25T09:00:00Z",
    riskLevel: "medium",
    affectedIndustries: ["食品", "化妆品", "医药", "日用品"],
  },
  {
    id: "pol-007",
    title: "Thailand Foreign Business Act Amendment",
    titleCn: "泰国《外商经营法》修正案",
    country: "TH",
    category: "外资准入",
    summary: "Thailand relaxes foreign ownership restrictions in selected sectors, opening opportunities for Chinese investors.",
    summaryCn: "泰国放宽部分行业外资持股限制，数字服务、可再生能源等领域外资持股上限从49%提升至75%。中国企业赴泰投资的准入门槛降低，但仍需遵守BOI投资促进委员会的审批流程。",
    content: "Thailand's amended Foreign Business Act raises foreign ownership limits from 49% to 75% in selected sectors including digital services, renewable energy, and advanced manufacturing. The Board of Investment (BOI) will fast-track applications from companies in promoted industries. However, land ownership restrictions and certain sector exclusions remain.",
    sourceUrl: "https://www.boi.go.th/",
    sourceName: "泰国投资促进委员会",
    publishedAt: "2026-02-20T08:00:00Z",
    riskLevel: "low",
    affectedIndustries: ["科技", "能源", "制造"],
  },
  {
    id: "pol-008",
    title: "EU Carbon Border Adjustment Mechanism (CBAM) Phase 2",
    titleCn: "欧盟碳边境调节机制(CBAM)第二阶段",
    country: "EU",
    category: "环保",
    summary: "EU expands CBAM to cover more product categories, requiring carbon emission reporting from importers.",
    summaryCn: "欧盟碳边境调节机制进入第二阶段，扩大征收范围至有机化学品、塑料制品等。中国出口企业需提供产品碳足迹数据，否则将按欧盟基准值征收碳关税。预计影响中国对欧出口额超500亿美元。",
    content: "The second phase of the EU CBAM expands coverage to organic chemicals, plastics, and additional manufactured goods. Importers must report embedded carbon emissions using verified data from producers. Where actual data is unavailable, default values based on worst-performing installations will be applied. Full financial obligations begin in this phase.",
    sourceUrl: "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism_en",
    sourceName: "欧盟税务与海关总署",
    publishedAt: "2026-02-15T12:00:00Z",
    riskLevel: "high",
    affectedIndustries: ["化工", "钢铁", "铝业", "塑料", "制造"],
  },
];

/** 模拟风险评估 */
export const mockRiskAssessments: RiskAssessment[] = [
  {
    id: "risk-001",
    country: "US",
    category: "贸易",
    riskLevel: "critical",
    title: "中美贸易摩擦持续升级",
    description: "美国持续加强对华出口管制和关税壁垒，半导体、AI、新能源等领域首当其冲。301条款关税仍在高位，实体清单持续扩大。",
    recommendation: "建议：1) 评估供应链对美依赖度 2) 建立替代供应商网络 3) 关注USTR听证会动态 4) 寻求专业贸易律师咨询",
    relatedPolicies: ["pol-002"],
    updatedAt: "2026-03-18T10:00:00Z",
  },
  {
    id: "risk-002",
    country: "EU",
    category: "数据保护",
    riskLevel: "high",
    title: "欧盟数据合规要求趋严",
    description: "GDPR执法力度加大，DMA/DSA新法规叠加，中国企业面临数据跨境传输、用户隐私保护等多重挑战。",
    recommendation: "建议：1) 聘请欧盟本地DPO 2) 完成数据保护影响评估(DPIA) 3) 建立欧盟境内数据中心 4) 制定数据泄露应急预案",
    relatedPolicies: ["pol-001"],
    updatedAt: "2026-03-17T14:00:00Z",
  },
  {
    id: "risk-003",
    country: "VN",
    category: "外资准入",
    riskLevel: "medium",
    title: "越南电商监管收紧",
    description: "越南加强跨境电商监管，要求设立本地实体和代扣代缴增值税。合规过渡期有限，需尽快行动。",
    recommendation: "建议：1) 尽快注册越南本地公司 2) 对接本地税务代理 3) 完善产品合规文件 4) 建立本地客服团队",
    relatedPolicies: ["pol-005"],
    updatedAt: "2026-03-16T09:00:00Z",
  },
  {
    id: "risk-004",
    country: "EU",
    category: "环保",
    riskLevel: "high",
    title: "碳关税影响中国制造出口",
    description: "CBAM第二阶段扩大覆盖范围，中国出口企业需提供碳足迹数据。缺乏准备的企业将面临额外成本。",
    recommendation: "建议：1) 开展产品碳足迹核算 2) 投资绿色生产技术 3) 获取ISO 14064认证 4) 与欧盟进口商沟通数据需求",
    relatedPolicies: ["pol-008"],
    updatedAt: "2026-03-15T11:00:00Z",
  },
  {
    id: "risk-005",
    country: "ID",
    category: "消费者保护",
    riskLevel: "medium",
    title: "印尼清真认证门槛提高",
    description: "印尼全面实施强制清真认证，覆盖食品、化妆品、药品等。认证流程复杂，周期3-6个月。",
    recommendation: "建议：1) 提前启动清真认证申请 2) 审查原材料供应链 3) 调整生产工艺确保合规 4) 聘请本地清真认证顾问",
    relatedPolicies: ["pol-006"],
    updatedAt: "2026-03-14T08:00:00Z",
  },
];

/** 模拟运营指南 */
export const mockGuides: OperationGuide[] = [
  {
    id: "guide-001",
    country: "US",
    category: "税务",
    title: "美国税务合规指南",
    content: "中国企业在美国开展业务需了解联邦税和州税两个层面。联邦企业所得税税率为21%，各州另有0%-12%不等的州税。销售税由各州自行规定，需要在有\"经济关联\"(nexus)的州注册征收。跨境电商需关注Wayfair案例确立的经济关联标准。",
    checklist: [
      "申请联邦雇主识别号(EIN)",
      "确定各州销售税征收义务",
      "注册州级营业税许可",
      "了解转让定价规则",
      "建立美国银行账户",
      "聘请本地会计师事务所",
      "按季度申报预估税款",
      "年度申报Form 1120(企业所得税)",
    ],
    lastUpdated: "2026-03-10T00:00:00Z",
  },
  {
    id: "guide-002",
    country: "EU",
    category: "数据保护",
    title: "欧盟GDPR合规指南",
    content: "《通用数据保护条例》(GDPR)适用于所有处理欧盟居民数据的企业，不论总部在何处。中国企业需指定欧盟代表，任命数据保护官(DPO)，并确保数据跨境传输的合法性基础。违规罚款最高可达全球年营业额的4%或2000万欧元。",
    checklist: [
      "指定欧盟境内代表",
      "任命数据保护官(DPO)",
      "完成数据保护影响评估(DPIA)",
      "建立数据处理记录(ROPA)",
      "实施数据主体权利响应流程",
      "确保数据跨境传输合规(SCC/BCR)",
      "制定数据泄露通知预案(72小时)",
      "定期开展员工隐私培训",
    ],
    lastUpdated: "2026-03-08T00:00:00Z",
  },
  {
    id: "guide-003",
    country: "JP",
    category: "劳工",
    title: "日本劳动法合规指南",
    content: "日本劳动法体系完善，对雇员保护力度大。中国企业在日设立分公司需遵守《劳动基准法》《劳动合同法》等。法定工作时间为每周40小时，加班需签订36协定。社会保险(健康保险、厚生年金等)为强制参加，企业和员工各承担约15%。",
    checklist: [
      "注册社会保险和劳动保险",
      "签订劳动合同(含试用期条款)",
      "制定就业规则(10人以上企业必须)",
      "签订36协定(加班协议)",
      "建立年假管理制度(最低10天)",
      "缴纳健康保险和厚生年金",
      "了解解雇保护制度",
      "办理外国人雇用届出",
    ],
    lastUpdated: "2026-03-05T00:00:00Z",
  },
  {
    id: "guide-004",
    country: "SG",
    category: "外资准入",
    title: "新加坡公司注册指南",
    content: "新加坡是中国企业出海的热门跳板。公司注册简便，通常1-2天完成。企业所得税17%，新创企业前3年有税收优惠。外资可100%持股，无外汇管制。但需至少一名本地董事，且公司秘书必须为新加坡常驻居民。",
    checklist: [
      "确定公司名称并查名",
      "准备注册文件(章程等)",
      "指定至少一名本地董事",
      "注册公司秘书",
      "注册办公地址(可用虚拟办公室)",
      "开设公司银行账户",
      "申请GST注册(年营业额超100万新元)",
      "申请必要的行业许可证",
    ],
    lastUpdated: "2026-03-01T00:00:00Z",
  },
];

/** 模拟案例 */
export const mockCases: CaseStudy[] = [
  {
    id: "case-001",
    title: "某跨境电商平台欧盟GDPR合规之路",
    company: "某知名跨境电商",
    industry: "电商",
    targetCountry: "EU",
    challenge: "该平台年交易额超百亿，在欧盟拥有数千万用户。2024年因数据泄露事件被爱尔兰DPC立案调查，面临巨额罚款风险。",
    solution: "公司组建了专门的欧盟合规团队，在爱尔兰设立数据中心，聘请本地DPO，全面梳理数据流并完成DPIA。投资约2000万元进行系统改造，实现用户同意管理、数据可携带等功能。",
    result: "通过12个月的整改，顺利通过DPC审查，罚款从预期的5000万欧元减少至200万欧元。建立了长效的数据保护体系，用户信任度提升，欧洲业务增长30%。",
    lessons: [
      "合规投入是必要的业务成本，越早越好",
      "本地化团队不可或缺，不能完全远程管理",
      "技术改造和流程建设需同步推进",
      "主动与监管机构沟通比被动应对更有效",
    ],
    publishedAt: "2026-02-20T00:00:00Z",
  },
  {
    id: "case-002",
    title: "中国新能源车企日本市场拓展实战",
    company: "某头部新能源车企",
    industry: "汽车",
    targetCountry: "JP",
    challenge: "日本汽车市场高度成熟，消费者对品质要求极高。中国品牌认知度低，售后服务网络空白，且日本消费者对国产车存在偏见。",
    solution: "采取\"技术先行、服务本地化\"策略：1) 与日本本地经销商合作建立销售网络 2) 投资建设右舵版本生产线 3) 在横滨设立研发中心 4) 聘请日本管理团队运营本地业务。",
    result: "进入日本市场首年销售3000辆，第二年增至1.2万辆。通过日本K-car标准认证，获得消费者好评。品牌认知度从0提升至15%。",
    lessons: [
      "深度本地化是进入日本市场的关键",
      "产品需针对日本市场做专门调整",
      "日本消费者重视售后服务胜过价格",
      "耐心建立品牌信任，不急于求成",
    ],
    publishedAt: "2026-02-10T00:00:00Z",
  },
  {
    id: "case-003",
    title: "SaaS企业东南亚多国扩张策略",
    company: "某企业级SaaS公司",
    industry: "科技",
    targetCountry: "SG",
    challenge: "东南亚市场碎片化严重，各国语言、法规、支付方式不同。以新加坡为总部辐射东南亚的策略面临本地化成本高、合规复杂度大的挑战。",
    solution: "采取\"新加坡总部+各国轻量级本地团队\"模式：1) 新加坡作为东南亚总部和控股公司 2) 印尼、泰国、越南设本地销售和支持团队 3) 产品实现多语言和多币种支持 4) 接入各国主流支付方式。",
    result: "两年内覆盖6个东南亚市场，ARR从200万美元增长至1500万美元。新加坡总部模式有效降低了税务成本，各国本地团队确保了客户服务质量。",
    lessons: [
      "新加坡是东南亚业务的理想总部选址",
      "各国合规要求差异大，需逐国评估",
      "本地支付接入是商业成功的关键",
      "轻资产模式适合初期市场探索",
    ],
    publishedAt: "2026-01-25T00:00:00Z",
  },
];

/** 订阅计划 */
export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: "free",
    name: "基础版",
    price: 0,
    priceLabel: "免费",
    features: [
      "3个国家政策监控",
      "基础AI解读（每月5次）",
      "风险等级提示",
      "社区访问",
    ],
  },
  {
    id: "pro",
    name: "专业版",
    price: 999,
    priceLabel: "¥999/月",
    features: [
      "全部10+国家政策监控",
      "无限AI深度解读",
      "实时风险预警推送",
      "完整运营指南库",
      "案例与最佳实践库",
      "专属行业分析报告",
      "优先客服支持",
    ],
    recommended: true,
  },
  {
    id: "enterprise",
    name: "企业版",
    price: -1,
    priceLabel: "定制报价",
    features: [
      "专业版全部功能",
      "API集成接口",
      "专属合规顾问",
      "定制风险评估报告",
      "企业培训服务",
      "SLA保障",
      "多账号管理",
    ],
  },
];
