/**
 * @fileoverview 格式化器单元测试
 */

import { AgentsFormatter } from '../src/formatters/agents-formatter';
import { AgentsConfig, ConfigSource, DirectiveCategory } from '../src/core/types';

describe('AgentsFormatter', () => {
  const formatter = new AgentsFormatter();

  const mockConfig: AgentsConfig = {
    version: '1.0.0',
    projectName: 'My Awesome Project',
    description: 'A modern web application',
    techStack: ['TypeScript', 'React', 'Node.js'],
    sections: [
      {
        title: 'Code Style & Formatting',
        category: DirectiveCategory.CODE_STYLE,
        directives: [
          {
            content: 'Use 2-space indentation',
            category: DirectiveCategory.CODE_STYLE,
            source: ConfigSource.CLAUDE_MD,
            priority: 7,
          },
          {
            content: 'Prefer const over let',
            category: DirectiveCategory.CODE_STYLE,
            source: ConfigSource.CURSORRULES,
            priority: 8,
          },
        ],
      },
      {
        title: 'Testing',
        category: DirectiveCategory.TESTING,
        directives: [
          {
            content: 'Write tests for all business logic',
            category: DirectiveCategory.TESTING,
            source: ConfigSource.CLAUDE_MD,
            priority: 9,
          },
        ],
      },
    ],
    sources: [ConfigSource.CLAUDE_MD, ConfigSource.CURSORRULES],
    generatedAt: '2024-01-01T00:00:00.000Z',
  };

  it('should format config to markdown string', () => {
    const output = formatter.format(mockConfig);

    expect(output).toContain('# My Awesome Project');
    expect(output).toContain('A modern web application');
    expect(output).toContain('version: 1.0.0');
    expect(output).toContain('TypeScript');
    expect(output).toContain('React');
    expect(output).toContain('Node.js');
  });

  it('should include sections with titles', () => {
    const output = formatter.format(mockConfig);

    expect(output).toContain('## Code Style & Formatting');
    expect(output).toContain('## Testing');
  });

  it('should include directives content', () => {
    const output = formatter.format(mockConfig);

    expect(output).toContain('Use 2-space indentation');
    expect(output).toContain('Prefer const over let');
    expect(output).toContain('Write tests for all business logic');
  });

  it('should sort directives by priority (highest first)', () => {
    const output = formatter.format(mockConfig);
    const constIndex = output.indexOf('Prefer const over let');
    const indentIndex = output.indexOf('Use 2-space indentation');

    expect(constIndex).toBeLessThan(indentIndex);
  });

  it('should include metadata section', () => {
    const output = formatter.format(mockConfig);

    expect(output).toContain('sources: CLAUDE.md, .cursorrules');
    expect(output).toContain('generated: 2024-01-01T00:00:00.000Z');
  });

  it('should include tech stack section', () => {
    const output = formatter.format(mockConfig);

    expect(output).toContain('## Tech Stack');
    expect(output).toContain('- TypeScript');
    expect(output).toContain('- React');
    expect(output).toContain('- Node.js');
  });

  it('should include footer', () => {
    const output = formatter.format(mockConfig);
    expect(output).toContain('Generated by [AgentSync]');
  });

  it('should handle empty sections gracefully', () => {
    const emptyConfig: AgentsConfig = {
      version: '1.0.0',
      projectName: 'Empty',
      description: '',
      techStack: [],
      sections: [],
      sources: [],
      generatedAt: '2024-01-01T00:00:00.000Z',
    };

    const output = formatter.format(emptyConfig);
    expect(output).toContain('# Empty');
    expect(output).not.toContain('## Tech Stack');
  });
});
