/**
 * @fileoverview init 命令 - 初始化 AGENTS.md 文件
 */

import { Command } from 'commander';
import * as fs from 'fs';
import * as path from 'path';

const TEMPLATE = `# Project Name

> Brief description of your project

---
version: 1.0.0
generated: ${new Date().toISOString()}
sources: manual
---

## Tech Stack

- Add your technologies here

## General Guidelines

- Add general coding guidelines here

## Code Style & Formatting

- Add code style rules here

## Architecture & Patterns

- Add architectural decisions here

## Testing

- Add testing requirements here

## Documentation

- Add documentation standards here

---

*Generated by [AgentSync](https://github.com/agentsync) v1.0.0*
`;

export const initCommand = new Command('init')
  .description('Create a new AGENTS.md file from template')
  .argument('[dir]', 'Project directory', '.')
  .option('-f, --force', 'Overwrite existing AGENTS.md')
  .option('--from-existing', 'Initialize from existing AI config files')
  .action((dir: string, options: { force?: boolean; fromExisting?: boolean }) => {
    const rootDir = path.resolve(dir);
    const outputPath = path.join(rootDir, 'AGENTS.md');

    if (fs.existsSync(outputPath) && !options.force) {
      console.log('\n  AGENTS.md already exists. Use --force to overwrite.\n');
      return;
    }

    if (options.fromExisting) {
      console.log('  Tip: Use `agentsync merge` to generate from existing config files.\n');
      return;
    }

    fs.writeFileSync(outputPath, TEMPLATE, 'utf-8');
    console.log('\n  ✓ Created AGENTS.md');
    console.log('  Edit the file to add your project-specific guidelines.\n');
  });
