import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { Recipe, Ingredient, Currency } from "@/types";
import { generateCostAnalysis } from "./costing";
import { formatCurrency, formatPercent } from "./utils";

/**
 * @description 生成定价标签 PDF
 * @param {Recipe} recipe - 食谱信息
 * @param {Ingredient[]} ingredients - 食材库
 * @param {Currency} currency - 货币类型
 */
export function generatePricingLabelPDF(
  recipe: Recipe,
  ingredients: Ingredient[],
  currency: Currency = "CNY"
): void {
  const analysis = generateCostAnalysis(recipe, ingredients);
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  doc.setFontSize(22);
  doc.setTextColor(5, 150, 105);
  doc.text("RecipeCost Pro", pageWidth / 2, y, { align: "center" });
  y += 8;
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text("Recipe Cost & Pricing Report", pageWidth / 2, y, {
    align: "center",
  });
  y += 12;

  doc.setDrawColor(5, 150, 105);
  doc.setLineWidth(0.5);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  doc.setFontSize(16);
  doc.setTextColor(30, 30, 30);
  doc.text(recipe.name, 20, y);
  y += 7;
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  if (recipe.description) {
    const descLines = doc.splitTextToSize(recipe.description, pageWidth - 40);
    doc.text(descLines, 20, y);
    y += descLines.length * 5 + 5;
  }

  const summaryData = [
    ["Servings", `${recipe.servings}`],
    ["Total Ingredient Cost", formatCurrency(analysis.totalCost, currency)],
    ["Cost per Serving", formatCurrency(analysis.perServingCost, currency)],
    ["Profit Margin", formatPercent(analysis.actualMargin)],
    ["Tax Rate", formatPercent(recipe.taxRate)],
    ["Suggested Price", formatCurrency(analysis.suggestedPrice, currency)],
    ["Profit per Serving", formatCurrency(analysis.profitPerServing, currency)],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Item", "Value"]],
    body: summaryData,
    theme: "grid",
    styles: { fontSize: 10, cellPadding: 4 },
    headStyles: {
      fillColor: [5, 150, 105],
      textColor: [255, 255, 255],
    },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 70 },
      1: { cellWidth: 80 },
    },
    margin: { left: 20, right: 20 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 12;

  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text("Ingredient Breakdown", 20, y);
  y += 4;

  const breakdownData = analysis.ingredientBreakdown.map((item) => [
    item.name,
    formatCurrency(item.cost, currency),
    formatPercent(item.percentage),
  ]);

  autoTable(doc, {
    startY: y,
    head: [["Ingredient", "Cost", "% of Total"]],
    body: breakdownData,
    theme: "grid",
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: {
      fillColor: [5, 150, 105],
      textColor: [255, 255, 255],
    },
    margin: { left: 20, right: 20 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 20;

  if (y > 250) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(16);
  doc.setTextColor(5, 150, 105);
  const priceLabel = `Suggested Price: ${formatCurrency(analysis.suggestedPrice, currency)}`;
  doc.text(priceLabel, pageWidth / 2, y, { align: "center" });

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by RecipeCost Pro | ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    285,
    { align: "center" }
  );

  doc.save(`${recipe.name}-pricing-label.pdf`);
}
